[features]
seeds = false
skip-lint = false

[programs.localnet]
s_pow_prog = "BHPKDZzNmf7gaLuSFJKcsSiAqhsCWPRHs98ao9TM673V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/nvt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
